#! /bin/bash

src=${1}
dst=${2}
files=`ls ${src}`
for file in ${files}
do
	srcfile="./${src}/${file}"
	dstfile="./${dst}/${file}"
	if test -f "${dstfile}"; then
#: << '#EOF'
		hash1=$(sha256sum ${srcfile} | awk '{print $1}')
		hash2=$(sha256sum ${dstfile} | awk '{print $1}')

		if [ "$hash1" = "$hash2" ]; then
			rm ${dstfile}
		fi
#EOF
	fi
done
